@extends('front.layouts.front')

@section('metatag')
    @if(!empty($seosetting))
    <title>{{$seosetting->meta_title}}</title>
    <meta name="title" content="{{$seosetting->meta_title}}">
    <meta name="description" content="{{$seosetting->meta_description}}">
    <meta name="keywords" content="{{$seosetting->meta_keyword}}">
    <meta name="robots" content="{{$seosetting->meta_robot}}">
    @else
    <title>Terms of Services</title>
    @endif
@endsection


@section('content')
<section class="content-bg">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm col-md-9 col-lg-8 col-xxl-7">
                <div class="content-area">
                    <h3>Terms</h3>
                    <p>Adults Only:</p>
                    <p>Welcome to worldofkink.com ("World of Kink"), owned, produced, and operated by Professional Idiots, Inc. ("PI"). World of Kink is a social network for people curious about exploring their sexuality. Unless explicitly stated otherwise, any current, updated and new products and services ("Products and Services"), including the addition of new properties, shall be subject to these General Terms and Conditions of Use ("Terms and Conditions").</p>
                    <p>In addition, there are a variety of special products and services offered through World of Kink that have separate registration procedures and separate terms and conditions, terms of service, user agreements, or similar legal agreements. When you are using any service or product of on World of Kink that does not have a separate legal agreement, the Terms and Conditions set forth here will apply. Professional Idiots also may supplement the Terms and Conditions with posted guidelines or rules applicable to specific areas of World of Kink. In addition, Professional Idiots and/or World of Kink also may offer other services from time to time that are governed by the terms of service of the respective service partners. Professional Idiots reserves the right to amend these Terms and Conditions at any time.</p>
                    <p>By using World of Kink you agree to be bound by these Terms and Conditions. Because the Terms and Conditions contain legal obligations, please read them carefully.</p>
                    <p>The Terms and Conditions contain a variety of provisions that are generally applicable to the Products and Services and some provisions that apply to particular Products and Services. You should understand that you will be bound by the entire Terms and Conditions.</p>
                    <ul>
                        <li>Acceptance</li>
                        <li>Conditions and Restrictions on Use</li>
                        <li>Registration & Privacy</li>
                        <li>User Conduct</li>
                        <li>License to User Content</li>
                        <li>Third-Party Merchandise Sales</li>
                        <li>Profiles</li>
                        <li>Disclaimer of Warranties</li>
                        <li>Limitation of Liability</li>
                        <li>Disclaimer Regarding Third Party Content</li>
                        <li>Storage</li>
                        <li>Advertisers and Content Linked to the World of Kink Network</li>
                        <li>No License; Intellectual Property of World of Kink and Others</li>
                        <li>Linking to World of Kink; Use of Logo</li>
                        <li>Indemnity and Release</li>
                        <li>Limitation of Actions</li>
                        <li>Copyright, Trademark, and Patent Notices</li>
                        <li>Intellectual Property Infringement Claims</li>
                        <li>Arbitration, Governing Law and Forum for Disputes</li>
                        <li>Changes in Terms and Conditions and Changes in Products and Services</li>
                        <li>Merger</li>
                        <li>Non-Waiver and Separability</li>
                        <li>Relationship of Parties</li>
                        <li>No Resale, Assignment or Sub-Licensing</li>
                        <li>Successors and Assigns</li>
                        <li>Termination; Survival</li>
                        <li>Communications with Users</li>
                        <li>Submission of Ideas</li>
                        <li>Export Controls</li>
                        <li>Violations and Terms and Conditions</li>
                    </ul>
                    <span>1. ACCEPTANCE</span>
                    <p>By using the Products and Services, you are agreeing, without limitation or qualification, to be bound by, and to comply with, these Terms and Conditions and any other posted guidelines or rules applicable to World of Kink or any Product or Service. All such guidelines and rules are hereby incorporated by reference into the Terms and Conditions.</p>
                    <span>2. CONDITIONS AND RESTRICTIONS ON USE</span>
                    <p>Use of the Products and Services is subject to compliance with these Terms and Conditions. You shall be authorized to use the Products and Services for personal, non-commercial use only. You acknowledge and agree that "PI" may terminate your access to the World of Kink or to any of the Products and Services should you fail to comply with the Terms and Conditions or any other guidelines and rules published by "PI" Any such termination shall be at "PI"' sole discretion and may occur without prior notice, or any notice.</p>
                    <p>"PI" further reserves the right to terminate any user's access to World of Kink or to any of the Products and Services for any conduct that "PI", at its sole discretion, believes is or may be directly or indirectly harmful to other users, to "PI" or its subsidiaries, affiliates, or business contractors, or to other third parties, or for any conduct that violates any local, provincial, federal or foreign laws or regulations. "PI" further reserves the right to terminate any user's access to World of Kink or to any of the Products and Services for any reason or for no reason at all, in "PI" sole discretion, without prior notice or any notice.</p>
                    <p>In order to use the Products and Services, users must have access to the World Wide Web and must navigate the Internet to <a href="https://worldofkink.com">https://worldofkink.com</a>. Individuals who are less than 18 years of age or are not permitted to access mature or adult content under the laws of any applicable jurisdiction may not access World of Kink. If "PI" learns that anyone under the age of 18 has accessed the Products and Services, "PI" will terminate their access to World of Kink.</p>
                    <p>"PI" does not discriminate on the basis of age, gender, race, ethnicity, nationality, religion, sexual orientation or any other protected status.</p>
                    <span>3. REGISTRATION AND PRIVACY</span>
                    <p>Certain of the Products and Services will require the user to register and provide certain data. In consideration of use of such Products and Services, in registering and providing such data, you represent and warrant that: (a) the information about yourself is true, accurate, current and complete (apart from optional items) as required by various "PI" registration forms ("Registration Data") and (b) you will maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or "PI" has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, "PI" has the right to suspend or terminate your account and refuse any and all current or future use of the Products and Services. <br>
                    All World of Kink registrations become the exclusive property of "PI". "PI" reserves the right to use and reuse all registration and other personally identifiable user information subject to "PI" Privacy Policy. Users may edit, update, alter or obscure their personally identifiable information at any time by following the instructions located on World of Kink.</p>
                    <p>You acknowledge receipt of the World of Kink Privacy Policy.</p>
                    <span>4. USER CONDUCT</span>
                    <p>You acknowledge and agree that all information, code, data, text, software, photographs, pictures, graphics, video, chat, messages, files, or other materials ("Content"), whether publicly posted or privately transmitted, are the sole responsibility of the person from which such Content originated. This means that you, and not "PI," are entirely responsible for all Content that you upload, post, email or otherwise transmit via the Services. "PI" does not control the user or third party Content posted via the Products and Services and, as such, does not guarantee the accuracy, integrity or quality of such user or third party Content.</p>
                    <p>You acknowledge and agree that by using the Products and Services, you may be exposed to Content that may be deemed offensive, indecent or objectionable. Nevertheless, you agree to use World of Kink at your sole risk. Under no circumstances will "PI" be liable in any way for any user or third party Content, including, but not limited to, for any errors or omissions in any such Content, or for any loss or damage of any kind incurred as a result of the use of any such Content posted, emailed or otherwise transmitted via the Products and Services.</p>
                    <p>As a general matter, "PI" does not screen user or third party Content posted on World of Kink, although "PI" reserves the right to do so. "PI" does not guarantee that any screening will be done to your satisfaction or that any screening will be done at all. "PI" reserves the right to monitor some, all, or no areas of the Products and Services for adherence to these Terms and Conditions or any other rules or guidelines posted by "PI" <br>
                    The Products and Services may only be used for the intended purpose for which such Products and Services are being made available.</p>
                    <p>You agree that, while using "PI" Products and Services,  you will not:</p>
                    <ul>
                        <li>Personally attack, make fun of, troll, flame, bully, stalk, or otherwise harass another member.</li>
                        <li>Make criminal accusations against another member in a public forum.</li>
                        <li>Make or promote any type of racism or hate towards anyone in specific or a group of people, unless in the context of role-playing between consenting parties.</li>
                        <li>Upload pictures or videos that contain any children under 18 years of age.</li>
                        <li>Upload, post, email, otherwise transmit or post links to any Content that promotes having any type of sexual relationship with a minor.</li>
                        <li>Create a user profile for a business, organization, website, or event that is not related to kink/swinging. Profiles for kink-related businesses will be reviewed and accepted on a case by case basis.</li>
                        <li>Take anything any other person has uploaded, posted, or emailed to you, on World of Kink and re-post such content anywhere outside of World of Kink without the expressed written permission of the person who uploaded, posted, or emailed you.</li>
                        <li>Upload, post, email, otherwise transmit, private conversations between two people in any public forum on World of Kink without the expressed written consent of the people who are involved in said private conversation.</li>
                        <li>Post, directly or indirectly, any personally identifying information about another member without their consent. Personally identifying information can include, but is not limited to, a person's full name, first name, last name, email address, profession, phone number, address, and place of work.</li>
                        <li>Use World of Kink to do any academic or corporate research without the expressed written consent of "PI"</li>
                        <li>Cross-post the same message, be it by one person or multiple people, more than 3 times a day.</li>
                        <li>Sexualize or publicly fantasize about the following topics: murder, animal abuse, and any activities involving minors. You may have strictly intellectual discussions regarding these topics.</li>
                        <li>Discuss or post content dealing with actual snuff, necrophilia, cannibalism, and zoophilia/bestiality. You may have strictly intellectual discussions regarding these topics, and may also have discussions and content concerning fantasies in these areas.</li>
                        <li>Create an event to promote a session with a phone sex operator, professional Dominant, or professional submissive.</li>
                        <li>Publicly post the schedule, price list, or phone number of a phone sex operator, professional Dominant, or professional submissive on World of Kink except in a group led by that person or in a group explicitly created for the purpose of posting such information.</li>
                        <li>Publicly solicit for clients on behalf, directly or indirectly, of phone sex operators, professional Dominants, and professional submissives in any group except in a group led by that person or in a group explicitly created for the purpose of posting such solicitations.</li>
                        <li>Solicit or sell any kind of sex for hire.</li>
                        <li>Use World of Kink for any fraudulent purposes.</li>
                        <li>Collect or store personally identifying information about any other user(s) for commercial purposes without the expressed consent of the user(s) or for any unlawful purposes.</li>
                        <li>Impersonate any person or entity, including, but not limited to, "PI" Inc or World of Kink Company official, employee, consultant, or otherwise, or falsely state or otherwise misrepresent your affiliation with a person or entity.</li>
                        <li>Employ misleading email addresses or falsify information in the header, footer, return path, or any part of any communication, including emails, transmitted through the Products and Services.</li>
                        <li>Upload, post, email, otherwise transmit, or post links to any Content that you do not have a right to transmit under any law or regulation or under contractual or fiduciary relationships (such as "inside information", or proprietary and confidential information learned or disclosed as part of employment relationships or subject to a nondisclosure agreement).</li>
                        <li>Upload, post, email, or otherwise transmit, or post links to any Content that facilitates computer hacking.</li>
                        <li>Upload, post, email, otherwise transmit, or post links to any Content that infringes any patent, trademark, service mark, trade secret, copyright or other proprietary rights ("Rights") of any party, or contributing to inducing or facilitating such infringement.</li>
                    </ul>
                    <p>This prohibition shall include, without limitation, the following forms of software piracy:</p>
                    <ul>
                        <li>Making available serial numbers for software that can be used to illegally validate or register software.</li>
                        <li>Making available tools that can be used for no purpose other than for "cracking" software or other copyrighted Content.</li>
                        <li>Making available any software files for which the user does not own the copyright or have the legal right to make available.</li>
                        <li>Making available copyrighted software or other Content that has had the copyright protection removed.</li>
                        <li>Upload, post, email, otherwise transmit, or post links to any unsolicited or unauthorized advertising, including but not limited to promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation, except in those areas that are designated for such purpose.</li>
                        <li>Upload, post, email, otherwise transmit, or post links to any material that contains software viruses, worms, trojan horses, time bombs, trap doors or any other computer code, files or programs or repetitive requests for information designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment or to diminish the quality of, interfere with the performance of, or impair the functionality of the Products and Services or World of Kink.</li>
                        <li>Use automated means, including additional computers, software and scripts, to enhance play in "PI" promotions.</li>
                        <li>Use automated means, including spiders, robots, crawlers, or the like to download data from any "PI" network database.</li>
                        <li>Use automated means, including bots, to create accounts on World of Kink.</li>
                        <li>Modify, publish, transmit, transfer or sell, reproduce, create derivative works from, distribute, link, display or in any way exploit any Content from any "PI" database, including, without limitation, by incorporating data from any "PI" database into any e-mail or "white pages" products or services, whether browser-based, based on proprietary client-site applications, web-based, or otherwise.</li>
                        <li>Sell, distribute, or make any commercial or unlawful use of data obtained from any "PI" database or make any other use of data from any "PI" database in a manner that could be expected to offend the person for whom the data is relevant.</li>
                        <li>Create and maintain a World of Kink profile that stores or hosts content for remote loading by other web pages. (For example, you cannot create a World of Kink profile, post pictures to the World of Kink profile, and have other web pages call the World of Kink profile to retrieve those pictures.)</li>
                        <li>Interfere with or disrupt the Products and Services or servers or networks connected to the Products and Services, or disobey any requirements, procedures, policies or regulations of networks connected to the Products and Services.</li>
                        <li>Intentionally or unintentionally violate any applicable local, state, national or international law, including, but not limited to, regulations promulgated by the Canadian or U.S. Securities and Exchange Commission, any rules of any national or other securities exchange, including, without limitation, the New York Stock Exchange, the American Stock Exchange or the NASDAQ, and any regulations having the force of law.</li>
                        <li>Upload, post, email, otherwise transmit, or post links to any material that is false, misleading, or designed to manipulate any equity, security, or other market.</li>
                        <li>Disobey any "PI" employee or representative or interfere with any action by any "PI"  employee or representative to redress any violation of these Terms and Conditions.</li>
                        <li>Create a new account in order to access the Products and Services after your account or access has been terminated by "PI"</li>
                        <li>Purchase any goods or services that you are prohibited from purchasing or possessing by any law applicable to you in your jurisdiction. The responsibility for ensuring compliance with all such laws shall be the user's alone. By submitting an order to purchase goods or services, you represent and warrant that you have the legal right to purchase such goods or services.</li>
                        <li>Use any software deployed in connection with the Products and Services to process data as a service to other entities without the express written consent of "PI" or the party from whom such software may be licensed.</li>
                        <li>Decompile, disassemble, modify, translate, adapt, reverse engineer, create derivative works from, or sub-license any software deployed in connection with the Products and Services.</li>
                        <li>Upload, post, email, otherwise transmit, or post links to any material, or act in any manner that is offensive to World of Kink community or the spirit of these Terms and Conditions.</li>
                    </ul>
                    <p>Advertise, offer for sale, or sell any of the following items:</p>
                    <ul>
                        <li>Any firearms, explosives, or weapons.</li>
                        <li>Any items that are hateful or racially, ethnically or otherwise objectionable, that contain child pornography, or are harmful to minors.</li>
                        <li>Any controlled substances or pharmaceuticals.</li>
                        <li>Any counterfeit or stolen items.</li>
                        <li>Any goods or services that do not, in fact, exist.</li>
                        <li>Any registered or unregistered securities.</li>
                        <li>Any items that violate or infringe the rights of other parties.</li>
                        <li>Any items that you do not have the legal right to sell.</li>
                        <li>Any items where paying "PI" any of the required transactional or listing fees would cause "PI" to violate any law.</li>
                    </ul>
                    <p>You acknowledge and agree that "PI" and its designees shall have the right (but not the obligation), in their sole discretion, to refuse to publish, remove, or block access to any Content that is available via the Products and Services at any time, for any reason, or for no reason at all, with or without notice. Without limitation, "PI" and its designees shall have the right (but not the obligation), at their sole discretion, to refuse to publish, remove, or block access to any Content that violates the Terms and Conditions or is otherwise objectionable as determined by "PI".</p>
                    <p>"PI" may also terminate access to, or membership in, World of Kink, or any portion thereof, for violating these Terms and Conditions. You acknowledge and agree that you must evaluate, and bear all risks associated with, the use of any Content, including any reliance on the accuracy, completeness, or usefulness of such Content. In this regard, you acknowledge that you may not rely on any Content created by or obtained through the use of World of Kink, including without limitation, information posted on message boards.</p>
                    <p>You expressly acknowledge and agree that "PI" may preserve Content and may also disclose Content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce the Terms and Conditions; (c) respond to claims that any Content violates the rights of third-parties; or (d) protect the rights, property, or personal safety of "PI", its users and the public. You acknowledge and agree that the technical processing and transmission of the Products and Services, including your Content, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. You further acknowledge and agree that other data collected and maintained by "PI" with regard to its users may be disclosed in accordance with "PI" <a href="#"> Privacy Policy</a>.</p>

                    <span>5. MEMBER OF THE MEDIA</span>
                    <p>I certify that I am not a member of the media, or that if I am, I am participating on World of Kink solely for my personal enjoyment and not as part of any investigation or gathering of information and that I will not use any such information in any manner without the express written permission of World of Kink. I agree that everything that I observe here will be kept in strict confidence, and that I will do nothing to jeopardize the privacy and identities of any other participant without the expressed written permission of World of Kink.</p>
                    <span>6. LIMITED LICENSE TO CONTENT POSTED ON WORLD OF KINK</span>
                    <p>"PI" claims no ownership interest in any of the Content (including, without limitation, pictures, videos and writing) posted by you on World of Kink, and the copyright to all such Content shall remain with its original owner.By posting Content on World of Kink, you warrant and represent that you own the Content posted by you or otherwise have the right to grant the license set forth in this section, and that such Content does not violate the rights of any third party. You agree to pay all royalties and fees owing to any person by reason of any Content you post on World of Kink.</p>
                    <p>In order to make it possible for "PI" to provide the Products and Services, you hereby grant "PI" a limited, non-exclusive, worldwide, royalty-free license to use, reproduce, modify (for example, re-sizing of photos and/or encoding of audio or video files), transmit, publicly display and distribute any Content posted by you on or through World of Kink, and to sublicense such rights solely as necessary to provide the Products and Services. The license shall terminate 30 days after you remove your Profile from World of Kink.</p>
                    <span>7. PAYMENT & REFUNDS</span>
                    <p>To request a refund you have to email support@worldofkink.com within 24 hours of the transaction and request a refund. Refunds will be for the full price of the transaction. "PI" does not refund any interest or transaction fees that might of been charged to you by your financial institution.</p>
                    <span>8. THIRD PARTY MERCHANDISE SALES</span>
                    <p>World of Kink may contain links to third party websites where Users can purchase goods or services from third party merchants ("Merchants"). By submitting an order to purchase any goods or services from Merchants, Users are obligated to complete such transactions, subject to the individual Merchant's terms and conditions governing such transactions. Users are prohibited from submitting orders to purchase goods or services where they do not intend to complete such transactions.</p>
                    <p>By submitting an order to purchase goods or services from an individual Merchant, you acknowledge that you are entering into a transaction with that Merchant, and that World of Kink, "PI" are not parties to the transaction.</p>
                    <p>Users are obligated to submit information that is true, accurate, current, and complete. By accepting these Terms and Conditions, you represent and warrant that all such information submitted by you is true, accurate, current, and complete. Users are also required to maintain and update all such information in order to ensure that it remains true, accurate, current, and complete. Each time you update such information, you represent and warrant that such information is true, accurate, current, and complete.</p>
                    <p>Users may not purchase goods or services that they are prohibited from purchasing or possessing by any law applicable to them in their jurisdictions. The responsibility for ensuring compliance with all applicable laws shall be the User's alone. By submitting an order to purchase goods or services, you represent and warrant that you have the legal right to purchase and possess such goods or services.</p>
                    <p>"PI" has no partnership, joint venture, employer-employee, or franchisor-franchisee relationship with any Merchant accessible through World of Kink. "PI" cannot confirm that any particular Merchant is who that Merchant claims to be. Nor can "PI" confirm the truth or accuracy of any statements made by Merchants or control whether Merchants who post statements on World of Kink will act in accordance with those statements. "PI" will not get involved in any dispute between Users of the Service and Merchants who post links on World of Kink. The ability to include links is provided only as a convenience, and the inclusion of any link by an Artist or User does not imply affiliation, endorsement, or adoption by "PI" of the linked site or any information contained therein.</p>
                    <span>9. PROFILES</span>
                    <p>Users are invited to post content to their profile ("Profile") subject to the following limitations: (a) "PI" may limit the amount of bandwidth dedicated to any account; and (b) "PI" reserves the right to display advertising on Profile pages. Please consult the World of Kink Privacy Policy for special terms as they relate to Profiles. Profiles are governed by the entire Terms and Conditions, including, without limitation, Section 5 (User Conduct), and you are encouraged to review these terms carefully. Under no circumstances may Profiles be used to infringe the copyright or any other right of any person or entity. "PI" reserves the right to modify or discontinue the Profiles service at any time, and you are encouraged to maintain backup copies of the content you post on your Profile. The Profile service may only be used by people who are at least 18 years old.<br>
                    By registering on World of Kink, you represent and warrant that all registration information you submit is truthful and accurate and that you will maintain the accuracy of such information. You further represent and warrant that you are 18 years of age or older and that your use of the World of Kink will not violate any applicable law. Your membership is for your sole, personal use, and you will not authorize others to use your account, including your Profile. You are solely responsible for all Content published or displayed through your account, and for your interactions with other Users. <br>
                    Please choose carefully the information you post on your Profile and that you provide to other members. Your Profile may not include the following items: telephone numbers and street addresses. Please read Section 4 above, User Conduct, for additional terms and conditions regarding your use of World of Kink.</p>
                    <p>The information provided by other users in their Profiles may contain inaccurate, inappropriate or offensive material, products or services for which "PI" assumes no responsibility or liability.</p>
                    <p>"PI" reserves the right, at its sole discretion, to reject, refuse to post or remove any Content posted by you, and to restrict, suspend, or terminate your access to all or any part of the "PI" Network, including World of Kink, at any time, for any or no reason, with or without prior notice, and without liability.</p>
                    <span>10. DISCLAIMER OF WARRANTIES</span>
                    <p>THE PRODUCTS AND SERVICES ARE PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER. ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS, ARE EXPRESSLY DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. TO THE FULLEST EXTENT PERMITTED BY LAW, "PI" DISCLAIMS ANY WARRANTIES FOR THE SECURITY, RELIABILITY, TIMELINESS, AND PERFORMANCE OF THE PRODUCTS AND SERVICES. TO THE FULLEST EXTENT PERMITTED BY LAW, "PI" DISCLAIMS ANY WARRANTIES FOR OTHER SERVICES OR GOODS RECEIVED THROUGH OR ADVERTISED ON THE PRODUCTS AND SERVICES OR RECEIVED THROUGH ANY LINKS PROVIDED IN THE PRODUCTS AND SERVICES, AS WELL AS FOR ANY INFORMATION OR ADVICE RECEIVED THROUGH THE PRODUCTS AND SERVICES OR THROUGH ANY LINKS PROVIDED IN THE PRODUCTS AND SERVICES. "PI" SIMILARLY DISCLAIMS, TO THE FULLEST EXTENT PERMITTED BY LAW, ANY WARRANTIES FOR ANY INFORMATION OR ADVICE OBTAINED THROUGH THE PRODUCTS AND SERVICES.</p>
                    <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT "PI" DISCLAIMS ANY AND ALL RESPONSIBILITY OR LIABILITY FOR THE ACCURACY, CONTENT, COMPLETENESS, LEGALITY, RELIABILITY, OR OPERABILITY OR AVAILABILITY OF INFORMATION OR MATERIAL IN THE PRODUCTS AND SERVICES. "PI" DISCLAIMS ANY RESPONSIBILITY FOR THE DELETION, FAILURE TO STORE, MISDELIVERY, OR UNTIMELY DELIVERY OF ANY INFORMATION OR MATERIAL. "PI" DISCLAIMS ANY RESPONSIBILITY OR LIABILITY FOR ANY HARM RESULTING FROM DOWNLOADING OR ACCESSING ANY INFORMATION OR MATERIAL THROUGH THE PRODUCTS AND SERVICES, INCLUDING, WITHOUT LIMITATION, FOR HARM CAUSED BY VIRUSES OR SIMILAR CONTAMINATION OR DESTRUCTIVE FEATURES. "PI" MAKES NO WARRANTY REGARDING THE RELIABILITY OR ACCESSIBILITY OF MEMBER WEB PAGES OR ANY STORAGE</p>
                    <span>FACILITIES OFFERED BY  "PI"</span>
                    <p>YOU UNDERSTAND AND AGREE THAT ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE PRODUCTS AND SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGES TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS IN THE DOWNLOAD OF SUCH MATERIAL.<br> Some jurisdictions do not allow the disclaimer of implied warranties. In such jurisdictions, the foregoing disclaimers may not apply to you insofar as they relate to implied warranties.</p>
                    <span>11. LIMITATION OF LIABILITY</span>
                    <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT UNDER NO CIRCUMSTANCES SHALL "PI" OR ITS LICENSORS BE LIABLE TO ANY USER ON ACCOUNT OF THAT USER'S USE OR MISUSE OF AND RELIANCE ON THE PRODUCTS AND SERVICES. SUCH LIMITATION OF LIABILITY SHALL APPLY TO PREVENT RECOVERY OF DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, AND PUNITIVE DAMAGES (EVEN IF "PI" OR ITS LICENSORS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES). SUCH LIMITATION OF LIABILITY SHALL APPLY WHETHER THE DAMAGES ARISE FROM USE OR MISUSE OF AND RELIANCE ON THE PRODUCTS AND SERVICES, FROM INABILITY TO USE THE PRODUCTS AND SERVICES, OR FROM THE INTERRUPTION, SUSPENSION, OR TERMINATION OF THE PRODUCTS AND SERVICES (INCLUDING SUCH DAMAGES INCURRED BY THIRD PARTIES).</p>
                    <p>SUCH LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF OTHER SERVICES OR GOODS RECEIVED THROUGH OR ADVERTISED ON THE PRODUCTS AND SERVICES OR RECEIVED THROUGH ANY LINKS PROVIDED IN THE PRODUCTS AND SERVICES, AS WELL AS BY REASON OF ANY INFORMATION OR ADVICE RECEIVED THROUGH OR ADVERTISED ON THE PRODUCTS AND SERVICES OR RECEIVED THROUGH ANY LINKS PROVIDED IN THE PRODUCTS AND SERVICES. SUCH LIMITATION SHALL APPLY, WITHOUT LIMITATION, TO THE COSTS OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, LOST PROFITS, OR LOST DATA. SUCH LIMITATION SHALL APPLY WITH RESPECT TO THE PERFORMANCE OR NON-PERFORMANCE OF THE PRODUCTS AND SERVICES OR ANY INFORMATION OR MERCHANDISE THAT APPEARS ON, OR IS LINKED OR RELATED IN ANY WAY TO WORLD OF KINK. SUCH LIMITATION SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. SUCH LIMITATION SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW.</p>
                    <p>SUCH LIMITATION OF LIABILITY SHALL ALSO APPLY TO ANY DAMAGE CAUSED BY LOSS OF ACCESS TO, DELETION OF, FAILURE TO STORE, FAILURE TO BACK UP, OR ALTERATION OF PROFILES, ARIST PAGES OR OTHER CONTENT STORED THROUGHOUT WORLD OF KINK.</p>
                    <p>UNDER NO CIRCUMSTANCES SHALL "PI" OR ITS LICENSORS BE HELD LIABLE FOR ANY DELAY OR FAILURE IN PERFORMANCE RESULTING DIRECTLY OR INDIRECTLY FROM ACTS OF NATURE, FORCES, OR CAUSES BEYOND ITS REASONABLE CONTROL, INCLUDING, WITHOUT LIMITATION, INTERNET FAILURES, COMPUTER EQUIPMENT FAILURES, TELECOMMUNICATION EQUIPMENT FAILURES, OTHER EQUIPMENT FAILURES, ELECTRICAL POWER FAILURES, STRIKES, LABOR DISPUTES, RIOTS, INSURRECTIONS, CIVIL DISTURBANCES, SHORTAGES OF LABOR OR MATERIALS, FIRES, FLOODS, STORMS, EXPLOSIONS, ACTS OF GOD, WAR, GOVERNMENTAL ACTIONS, ORDERS OF DOMESTIC OR FOREIGN COURTS OR TRIBUNALS, NON-PERFORMANCE OF THIRD PARTIES, OR LOSS OF OR FLUCTUATIONS IN HEAT, LIGHT, OR AIR CONDITIONING.
                        <br>
                    In some jurisdictions, limitations of liability are not permitted. In such jurisdictions, the foregoing limitation may not apply to you.</p>
                    <span>12. DISCLAIMER REGARDING THIRD PARTY CONTENT</span>
                    <p>World of Kink offers access to numerous third party web pages and content available over the Internet. In overwhelming majority instances, including, but not limited to, sites contained within a directory of links, "PI" has no control whatsoever over the content of such sites. In other instances, including, but not limited to, web pages hosted on World of Kink or provided to World of Kink by third parties, "PI" may set guidelines for what may appear on such web pages and may engage in certain screening, but generally exercises no control over the content of such web pages and is unable to police all such content.</p>
                    <p>Third party content accessible through World of Kink from such sources is developed by people over whom World of Kink exercises no control. Similarly, content hosted by World of Kink which is posted by third parties, and, with the exception of certain random screening functions, "PI" cannot and does not screen such web pages before they are made accessible to other users of World of Kink. Accordingly, neither "PI" nor its licensors assume any responsibility for the content of any site linked to the World of Kink web site or in any web page hosted for a third party within World of Kink web site. In instances where World of Kink does review the sites that are displayed in directories, indices, and/or references, or where World of Kink makes available directories, indices, and/or references of sites compiled by third parties, the content located at such sites was developed third parties, and review of such sites by "PI", if any, is narrowly limited to that which is necessary for compiling the particular set of links.</p>
                    <span>13. STORAGE</span>
                    <p>Many features of World of Kink store information on behalf of users. Examples include, but are not limited to chat, Profiles and postings. "PI" reserves the right, in its sole discretion, to limit the amount of storage space available per user or to delete materials stored for an excessive period while the user's account has been inactive.</p>
                    <span>14. ADVERTISERS AND CONTENT LINKED TO THE WORLD OF KINK NETWORK</span>
                    <p>"PI" and the World of Kink Companies may provide, or third parties may provide, links to other sites or resources located on the World Wide Web by allowing a user to leave World of Kink to access third-party material or by bringing the third party material into this site via "inverse" hyperlinks and framing technology. "PI" have no control over such sites and resources. You acknowledge and agree that "PI" are not responsible for the availability of such external sites or resources, and do not endorse and are not responsible or liable for any content, advertising, products, or other materials on or available from such sites or resources. You further acknowledge and agree that "PI" shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.</p>
                    <p>Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the World of Kink Products and Services, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. You agree that "PI" shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Product and Services.</p>
                    <span>15. NO LICENSE; INTELLECTUAL PROPERTY OF WORLD OF KINK AND OTHERS</span>
                    <p>Except as expressly provided, nothing within any of the Products and Services shall be construed as conferring any license under any of "PI" or any third party's intellectual property rights, whether by estoppel, implication, waiver, or otherwise. Without limiting the generality of the foregoing, you acknowledge and agree that certain Content available through and used to operate World of Kink and the Products and Services is protected by copyright, trademark, patent, or other proprietary rights of "PI" and its affiliates, licensors (including, without limitation, Artists), and service providers. Except as expressly provided to the contrary, you agree not to modify, alter, or deface any of the trademarks, service marks, or other intellectual property made available by "PI" in connection with the Products and Services. You agree not to hold yourself out as in any way sponsored by, affiliated with, or endorsed by "PI", any of "PI" affiliates, or any of "PI" service providers. You agree not to use any of the trademarks or service marks or other Content accessible through World of Kink for any purpose other than the purpose for which such Content is made available to users by "PI" You agree not to defame or disparage "PI", the trademarks or service marks of "PI", or any aspect of the Products and Services. You agree not to adapt, translate, modify, decompile, disassemble, or reverse engineer the Products and Services or any software or programs used in connection with the Products and Services or World of Kink.</p>
                    <p>In order to maintain the privacy and security of your user profile, you hereby grant "PI" a limited, non-exclusive, worldwide, royalty-free license to any and all copyrightable content posted by you on or through World of Kink.  You also grant and assign "PI" or its affiliates the right and authority to enforce your DMCA and any and all intellectual property rights against alleged infringers at your request.  This provision does not constitute in any way a partnership, joint venture or any other fiduciary relationship between you and "PI"  Further, "PI" does not warrant or guarantee that it can or will enforce your intellectual property rights against alleged infringers.  "PI" reserves the right through this limited license to enforce your rights at your request, however, it remains the sole and primary responsibility of each member, the Content creator, and owner, to police and enforce your rights against alleged infringers. ​</p>
                    <span>16. LINKING TO WORLD OF KINK; USE OF LOGO</span>
                    <p>World of Kink offers a non-assignable, non-transferable, and non-exclusive license to link to World of Kink websites, using World of Kink logos, subject to the following provisions. World of Kink logos may be placed on a Web site for the sole purpose of creating a link to World of Kink and allowing users of your site to access the Products and Services on World of Kink. World of Kink logos may not be used for any other purpose, including, among other purposes, to suggest sponsorship by, or affiliation with, or endorsement by World of Kink. World of Kink logos may only be used in accordance with the "PI" Trademark Usage Guidelines, and may only be used in the exact size, shape, colors, design, and configuration as found on such web page. World of Kink logos may not be altered in any manner. World of Kink logos must appear by themselves, with reasonable spacing (at least the height of the logo) between each side of the applicable logo and other graphic or textual elements. World of Kink logos may not be used to disparage World of Kink, its products or services, or in a manner which, in "PI" reasonable judgment, may diminish or otherwise damage "PI" goodwill in World of Kink logos. By using any such "PI" Network logo, you acknowledge that World of Kink has exclusive rights to the logo and that all goodwill generated through your use of the logo will inure to the benefit of World of Kink. If you use World of Kink logos, you must include appropriate attribution, for example: "World of Kink is a trademark of "PI".  "PI" reserves the right to revoke this license or to alter its terms from time to time, for any or no reason, with or without notice. "PI" reserves the right to take action against any use that does not conform to these provisions.</p>
                    <span>17. INDEMNITY AND RELEASE</span>
                    <p>By using the World of Kink website you agree to indemnify "PI", and their officers, employees, volunteers and licensors, and hold them harmless from any and all claims and expenses, including attorney's fees, arising from your use of the World of Kink web site, your use of the Products and Services, or your submission of ideas and/or related materials to "PI" or from any person's use of any account or password you maintain with World of Kink, regardless of whether such use is authorized by you. By using World of Kink, using the Products and Services, or submitting any ideas and/or related materials to "PI" you are hereby agreeing to release "PI" and its parents, subsidiaries, affiliates, officers, employees, volunteers, and licensors from any and all claims, demands, debts, obligations, damages (actual or consequential), costs, and expenses of any kind or nature whatsoever, whether known or unknown, suspected or unsuspected, disclosed or undisclosed, that you may have against them arising out of or in any way related to such disputes and/or to the Products and Services or to any disputes regarding use of ideas and/or related materials submitted to "PI" YOU HEREBY AGREE TO WAIVE ALL LAWS THAT MAY LIMIT THE EFFICACY OF SUCH RELEASES. ​</p>
                    <span>18. LIMITATION OF ACTIONS</span>
                    <p>You acknowledge and agree that, regardless of any statute or law to the contrary, any claim or cause of action you may have arising out of, or relating to, your use of World of Kink or the Products and Services must be filed within one (1) year after such claim or cause of action arises, or forever be barred.</p>
                    <span>19. COPYRIGHT, TRADEMARK, AND PATENT NOTICES</span>
                    <p>All other marks that appear throughout the Products and Services belong to "PI" or the respective owners of such marks, and are protected by U.S. and international copyright and trademark laws. Any use of any of the marks appearing throughout the Products and Services without the express written consent of "PI" or the owner of the mark, as appropriate, is strictly prohibited. "PI" may provide, or third parties may provide, links to other sites or resources located on the World Wide Web by allowing a user to leave World of Kink to access third-party material or by bringing the third party material into this site via "inverse" hyperlinks and framing technology. "PI"  have no control over such sites and resources. You acknowledge and agree that "PI" are not responsible for the availability of such external sites or resources, and do not endorse and are not responsible or liable for any content, advertising, products, or other materials on or available from such sites or resources. You further acknowledge and agree that "PI" shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.</p>
                    <p>Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the World of Kink Products and Services, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. You agree that "PI" shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Product and Services.</p>
                    <span>20. INTELLECTUAL PROPERTY INFRINGEMENT CLAIMS</span>
                    <p>"PI" respects the intellectual property of others. It is "PI" policy to respond expeditiously to claims of copyright and other intellectual property infringement. "PI" will promptly process and investigate notices of alleged infringement and will take appropriate actions under the Digital Millennium Copyright Act ("DMCA") and other applicable intellectual property laws. Upon receipt of notices complying or substantially complying with the DMCA, "PI" may act expeditiously to remove or disable access to any material claimed to be infringing or claimed to be the subject of infringing activity and may act expeditiously to remove or disable access to any reference or link to material or activity that is claimed to be infringing. "PI" will terminate access for users who are repeat infringers.</p>
                    <p>Notifying "PI" of Copyright Infringement: To provide "PI" notice of an infringement, you must provide a written communication to the attention of "DMCA Infringement Notification Dept." care of <a href="legal@worldofkink.com">legal@worldofkink.com</a> legal@worldofkink.com that sets forth the information specified by the DMCA ( <a href=" https://www.copyright.gov/title17/92chap5.html#512" target="_blank"> https://www.copyright.gov/title17/92chap5.html#512</a>). Please note that you may be liable for damages (including costs and attorneys' fees) if you materially misrepresent that an activity is infringing your copyright.</p>
                    <p>Providing "PI" with Counter-Notification: If you feel that your material does not constitute infringement, you may provide "PI" with a counter notification by written communication to the attention of "DMCA Counter Notification Dept." at legal@worldofkink.com that sets forth all of the necessary information required by the DMCA<br>(<a href="https://www.copyright.gov/title17/92chap5.html#512">https://www.copyright.gov/title17/92chap5.html#512</a> ). Please note that you may be liable for damages (including costs and attorneys' fees) if you materially misrepresent that an activity is not infringing the copyrights of others. If you are uncertain whether an activity constitutes infringement, we recommended seeking advice of legal counsel.</p>
                    <span>21. ARBITRATION, GOVERNING LAW AND FORUM FOR DISPUTES</span>
                    <p>Unless expressly stated to the contrary elsewhere within the Products and Services, all legal issues arising from or related to the use of the Products and Services shall be construed in accordance with, and all questions with respect thereto shall be determined by, the laws of Douglas County Colorado, applicable to contracts entered into and wholly to be performed within said province. Any controversy or claim arising out of or relating to these Terms and Conditions or any user's use of the Products and Services shall be settled by binding arbitration in accordance with the commercial arbitration rules of the Arbitration and Mediation Institute of America. Any such controversy or claim shall be arbitrated on an individual basis, and shall not be consolidated in any arbitration with any claim or controversy of any other party. The arbitration shall be conducted in Denver, Colorado, and judgment on the arbitration award may be entered into in any provincial or federal court in British Columbia having jurisdiction thereof. Any party seeking temporary or preliminary injunctive relief may do so in any provincial or federal court in Denver, Colorado having jurisdiction thereof. Except as set forth above, the provincial and federal courts of Denver, Colorado shall be the exclusive forum and venue to resolve disputes arising out of or relating to these Terms and Conditions or any user's use of the Products and Services. By using the Products and Services and thereby agreeing to these Terms and Conditions, users consent to personal jurisdiction and venue in the provincial and federal courts in Denver, Colorado with respect to all such disputes.</p>
                    <span>22. CHANGES IN TERMS AND CONDITIONS AND CHANGES IN PRODUCTS AND SERVICES</span>
                    <p>"PI" reserves the right to modify the Products and Services from time to time, for any reason, and without notice, including the right to terminate the Products and Services. "PI" reserves the right to modify these Terms and Conditions from time to time, without notice. Please review these Terms and Conditions from time to time so you will be apprised of any changes.</p>
                    <span>23. MERGER</span>
                    <p>These Terms and Conditions constitute the entire agreement between the parties with respect to the subject matter contained herein and supersede any other agreements, proposals and communications, written or oral, between "PI" representations and you with respect to the subject matter hereof; except that any other terms and conditions located on any individual "PI" web site or in connection with the Products and Services are incorporated herein by reference to the extent they do not conflict with these Terms and Conditions. To the extent that any other terms and conditions or terms of service conflict with these Terms and Conditions, those other provisions shall control with respect to the use of the particular web site and any Products or Services available on or through the web site or the respective Product or Service at which those other provisions may be found.</p>
                    <span>24. NON-WAIVER AND SEPARABILITY</span>
                    <p>"PI" failure to exercise any right or provision of these Terms and Conditions shall not constitute a waiver of such right or provision. If a court of competent jurisdiction holds any provision of these Terms and Conditions to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and agree that the other provisions of these Terms and Conditions remain in full force and effect.</p>
                    <span>25. RELATIONSHIP OF PARTIES</span>
                    <p>You acknowledge and agree that you and "PI" are independent contractors under these Terms and Conditions, and nothing herein shall be construed to create a partnership, joint venture, agency, or employment relationship. Neither party pursuant to these Terms and Conditions has authority to enter into agreements of any kind on behalf of the other and neither party shall be considered the agent of the other.</p>
                    <span>26. NO RESALE, ASSIGNMENT, OR SUBLICENSING</span>
                    <p>You agree not to resell, assign, sublicense, otherwise transfer, or delegate your rights or obligations under these Terms and Conditions without prior express written authorization of "PI".</p>
                    <span>27. SUCCESSORS AND ASSIGNS</span>
                    <p>Without in any way limiting the prohibition on your resale, assignment, sublicensing, or other transfer of rights or obligations, these Terms and Conditions shall be binding upon and inure to the benefit of the parties hereto and their respective heirs, successors, and assigns.</p>
                    <span>28. TERMINATION; SURVIVAL</span>
                    <p>These Terms and Conditions shall continue in effect for as long as you use the Products and Services, unless specifically terminated earlier by "PI" All provisions of these Terms and Conditions which impose obligations continuing in their nature shall survive termination of these Terms and Conditions.</p>
                    <span>29. COMMUNICATIONS WITH USERS</span>
                    <p>You consent to receive communications from "PI" concerning your use of the Products and Services ("Communications"). The Communications may be those that "PI" is required to send to you by law concerning the Products and Services ("Required Communications"). The Communications may also be those that "PI" sends to you for other reasons. You consent to receive Communications electronically. "PI" may provide these Communications to you by sending an email to the email address you provided in connection with your account or by posting the Communication on World of Kink. You may change the email address to which "PI" sends Communications by visiting your account information page.</p>
                    <p>In order to receive Required Communications, you must provide "PI", upon registration with World of Kink, a valid email address to which "PI" may send electronic mail.</p>
                    <span>30. SUBMISSIONS OF IDEAS</span>
                    <p>World of Kink is always improving its Products and Services and developing new features. If you have ideas regarding improvements or additions to World of Kink, we would like to hear them -- but any submission will be subject to these Terms and Conditions.</p>
                    <p>UNDER NO CIRCUMSTANCES SHALL ANY DISCLOSURE OF ANY IDEA OR RELATED MATERIALS TO WORLD OF KINK BE SUBJECT TO ANY OBLIGATION OF CONFIDENTIALITY OR EXPECTATION OF COMPENSATION. BY SUBMITTING THE IDEA AND/OR ANY RELATED MATERIAL TO "PI", YOU ARE WAIVING ANY AND ALL RIGHTS THAT YOU MAY HAVE IN THE IDEA OR ANY RELATED MATERIALS AND ARE REPRESENTING AND WARRANTING TO "PI" THAT THE IDEA AND/OR RELATED MATERIALS ARE WHOLLY ORIGINAL WITH YOU, THAT NO ONE ELSE HAS ANY RIGHTS IN THE IDEA AND/OR MATERIALS AND THAT "PI" IS FREE TO IMPLEMENT THE IDEA AND TO USE THE MATERIALS IF IT SO DESIRES, AS PROVIDED OR AS MODIFIED BY "PI", WITHOUT OBTAINING PERMISSION OR LICENSE FROM ANY THIRD PARTY.</p>
                    <span>31. EXPORT CONTROLS</span>
                    <p>Certain software, and related documentation or technical information, available through World of Kink is subject to applicable laws and regulations of the United States pertaining to export controls. By using such software or related documentation or technical information, you represent and warrant that you are not located in, or under the control of, or a national or resident of any embargoed country or any country on the U.S. Department of Commerce's Table of Denial Orders. You agree not to export or re-export such software or related documentation or technical information directly or indirectly to any countries that are subject to United States export restrictions.</p>
                    <span>32. CONTACT INFORMATION</span>
                    <p>You can find all of our detailed contact information on our page.<br> For your convenience, we've also included our basic contact information here:</p>
                    <p>Professional Idiots, Inc<br>
                        PO Box 1388<br>
                        Castle Rock, Colorado 80104</p>
                    <p>For the quickest response, email us at support@worldofkink.com.</p>
                    <span>33. VIOLATIONS OF TERMS AND CONDITIONS</span>
                    <p>Should you violate these Terms and Conditions or any other rights of "PI". "PI" reserve the right to pursue any and all legal and equitable remedies against you, including, without limitation, terminating any and all user accounts on any and all "PI" properties.<br>
                    If you are aware of any violations of these Terms and Conditions, please report them to: legal@worldofkink.com.</p>
                    <p>Please read the entire Terms and Conditions, as all "PI" properties, Products and Services are offered subject to these Terms and Conditions.</p>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection


@section('page-scripts')
@endsection
